import { ShotArchetype, ShotArchetypeId } from '../types/camera';

export const SHOT_ARCHETYPES: Record<ShotArchetypeId, ShotArchetype> = {
  'ootd-full': {
    id: 'ootd-full',
    title: 'OOTD / Full Body',
    subtitle: 'Elongate legs & show the whole fit',
    badge: 'OOTD',
    iconName: 'User',
    targetPitchDeg: 6.0, // Tilted slightly up towards sky
    pitchToleranceDeg: 3.5,
    targetRollDeg: 0.0,
    rollToleranceDeg: 2.0,
    heightHint: 'Waist / Stomach Height',
    lensPreference: '1x',
    headroomPercentage: 0.12,
    feetMarginPercentage: 0.08,
    proTip: 'Hold phone at belly-button level and tilt the top back slightly towards you.',
  },
  'portrait-half': {
    id: 'portrait-half',
    title: 'Half Body / Portrait',
    subtitle: 'Upper-third eye line & crisp depth',
    badge: 'PORTRAIT',
    iconName: 'Smile',
    targetPitchDeg: 1.0,
    pitchToleranceDeg: 3.0,
    targetRollDeg: 0.0,
    rollToleranceDeg: 1.5,
    heightHint: 'Chest / Eye Height',
    lensPreference: '2x',
    headroomPercentage: 0.15,
    feetMarginPercentage: 0.35,
    proTip: 'Align her eyes with the upper dashed line. Move closer rather than zooming in excessively.',
  },
  'cafe-sitting': {
    id: 'cafe-sitting',
    title: 'Cafe / Table Sitting',
    subtitle: 'Flattering angle with coffee/food context',
    badge: 'CAFE',
    iconName: 'Coffee',
    targetPitchDeg: -3.5, // Slight downward angle over table
    pitchToleranceDeg: 3.0,
    targetRollDeg: 0.0,
    rollToleranceDeg: 2.0,
    heightHint: 'Table / Seated Level',
    lensPreference: '1x',
    headroomPercentage: 0.14,
    feetMarginPercentage: 0.25,
    proTip: 'Sit or crouch down to her table level. Never take this photo standing above her.',
  },
  'aesthetic-wide': {
    id: 'aesthetic-wide',
    title: 'Scenery / Architecture',
    subtitle: 'Vibe shot with beautiful surroundings',
    badge: 'SCENERY',
    iconName: 'Camera',
    targetPitchDeg: 0.0,
    pitchToleranceDeg: 2.5,
    targetRollDeg: 0.0,
    rollToleranceDeg: 1.5,
    heightHint: 'Chest / Eye Height',
    lensPreference: '0.5x',
    headroomPercentage: 0.20,
    feetMarginPercentage: 0.10,
    proTip: 'Strictly level horizon is critical. Keep vertical lines upright without keystone distortion.',
  },
  'golden-hour': {
    id: 'golden-hour',
    title: 'Golden Hour Glow',
    subtitle: 'Backlit rim light & flare management',
    badge: 'GLOW',
    iconName: 'Sun',
    targetPitchDeg: 3.0,
    pitchToleranceDeg: 3.0,
    targetRollDeg: 0.0,
    rollToleranceDeg: 2.0,
    heightHint: 'Chest / Eye Height',
    lensPreference: '1x',
    headroomPercentage: 0.15,
    feetMarginPercentage: 0.15,
    proTip: 'Position the sun directly behind her hair or shoulder to avoid washed-out lens flare.',
  },
};

export const ARCHETYPE_LIST: ShotArchetype[] = Object.values(SHOT_ARCHETYPES);
export const DEFAULT_ARCHETYPE: ShotArchetype = SHOT_ARCHETYPES['ootd-full'];
